### ISSUE TITLE
Rework projectile explosions

### ISSUE THREAD

**Issue by jaks6** [Stopa/Mobile-Defence-Fortress#61]
Currently, the explosions work like something as follows:
1) The projectile collides with something, the projectile's .collide() method is called.
2) a setTimeout is called, at the end ofwhich the projectile's this._die() is called. Simultaneously, an animation is started where the explosion is scaled each tick
3) During the timeout and animation, the projectile is still alive and keeps colliding with objects - this is the problem.

To fix this, one proposal is to create new Explosion / ImpactAnimation class. Once a projectile collides, the projectile should immediately die to avoid further collisions and a new instance of this explosion class is to be created. The explosion graphics would thus be cosmetical.

The above idea is just ONE way to solve this.

**Comment by xenover** [comment]
Will look into it
